- name: linux setup
  hosts: "{{ host }}"
  vars:
    apps:
      - discord
      - knowte
      - 1password
      - postman
      - signal-desktop

    classic_apps:
      - android-studio

    packages:
      - git
      - ansible
      - quiterss
      - xclip
      - vim
      - conky-all
      - testdisk
      - curl
      - tldr
      - zsh
      - fonts-powerline

    github_url: "https://github.com/ElQwerto110100100/toolbox"

    fav_theme: "Yaru-dark"

    fav_toolbar: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', '1password_1password.desktop', 'install4j_a177y-BurpSuiteCommunity.desktop', 'discord_discord.desktop', 'gnome-control-center.desktop']"

  config_files: 
    .conky: "~/.conkyrc"
    conky.desktop: "~/.config/autostart/conky.desktop"
    my-feeds.opml: "~/Documents"
    weather.desktop: "~/.config/autostart/weather.desktop"

  tasks:
    - name: "Root Tasks"
      block:
        - name: "Update all packages to their latest version"
          apt:
            name: "*"
            state: latest

        - name: "Upgrade the OS (apt-get dist-upgrade)"
          apt:
            upgrade: dist

        - name: "Install classic snaps"
          snap:
            name: "{{ item }}"
          loop: "{{  classic_apps }}"

        - name: "Install other snaps"
          snap:
            name: "{{ item }}"
          loop: "{{ apps }}"

        - name: "Installing packages"
          apt:
            name: "{{ item }}"
          loop: "{{ packages }}"
          tags: vim

        - name: "Get git toolbox"
          git:
            repo: "{{ github_url }}"
            dest: ~/tools/linux_tools/

        - name: "Set 'sensible' vim config folder"
          file:
            state: directory
            path: ~/.vim/pack/tpope/start
          tags: vim

        - name: "Get 'sensible' vim congif repo"
          git:
            repo: "https://tpope.io/vim/sensible.git"
            dest: ~/.vim/pack/tpope/start
          tags: vim
      become: yes

    - name: "non root tasks"
      block:
        - name: "Make tools dir"
          file:
            state: directory
            path: ~/tools

        - name: "Set dark theme"
          command: "gsettings set org.gnome.desktop.interface gtk-theme '{{ fav_theme }}'"

        - name: "Set favourite toolbar"
          command: 'gsettings set org.gnome.shell favorite-apps "{{ fav_toolbar }}" '
          tags: "toolbar"

        - name: "nvm"
          shell: >
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          args:
            creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

        - name: "Import vim config"
          copy:
            src: ./files/.vimrc
            dest: ~/.vimrc
          tags: vim

        - name: "Install vim plugins and coc exstentions"
          command: 'vim -c :PlugInstall && vim -c ":source $MYVIMRC" && vim -c "CocInstall -sync coc-json coc-html coc-tsserver coc-prettier coc-css|q"'

        - name: "Installing Oh My Zsh"
          shell: >
            sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

        - name: "Install zsh auto surgesstions"
          git:
            repo: 'https://github.com/zsh-users/zsh-autosuggestions'
            desx: "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"

        - name: "Add fasd apt repo"
          apt_repository:
            repo: "ppa:aacebedo/fasd"
        
        - name: "install fasd"
         apt:
          name: "fasd"

        - name: "config files"
          copy:
            src: "./files/{{ item.key }}"
            dest: "{{ item.value }}"
          with_dict: "{{ config_files  }}"

