- name: linux setup
  hosts: "{{ host }}"
  vars_files:
    - ./vars/items.yml
 
  tasks:
    - name: "Root Tasks"
      block:
        - name: "Update all packages to their latest version"
          apt:
            name: "*"
            state: latest

        - name: "Upgrade the OS (apt-get dist-upgrade)"
          apt:
            upgrade: dist

        - name: "Install other snaps"
          snap:
            name: "{{ item }}"
          loop: "{{ apps }}"

        - name: "Installing packages"
          apt:
            name: "{{ item }}"
          loop: "{{ packages }}"
          tags: vim

        - name: "Get git toolbox"
          git:
            repo: "{{ github_url }}"
            dest: ~/tools/linux_tools/

      become: yes

    - name: "non root tasks"
      block:
        - name: "Make tools dir"
          file:
            state: directory
            path: ~/tools

        - name: "Set dark theme"
          command: "gsettings set org.gnome.desktop.interface gtk-theme '{{ fav_theme }}'"

        - name: "Set favourite toolbar"
          command: 'gsettings set org.gnome.shell favorite-apps "{{ fav_toolbar }}" '
          tags: "toolbar"

        - name: "nvm"
          shell: >
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          args:
            creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

        #- name: "Install vim plugins and coc exstentions"
        #command: 'vim -c :PlugInstall && vim -c ":source $MYVIMRC" && vim -c "CocInstall -sync coc-json coc-html coc-tsserver coc-prettier coc-css coc-yaml|q"'

        - name: "Installing Oh My Zsh"
          shell: >
            sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

        - name: "Install zsh auto surgesstions"
          git:
            repo: 'https://github.com/zsh-users/zsh-autosuggestions'
            dest: "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"

        - name: "Add fasd apt repo"
          apt_repository:
            repo: "ppa:aacebedo/fasd"
        
        - name: "install fasd"
          apt:
            name: "fasd"

        - name: "download dotfiles"
          git:
            repo: "{{dotfiles_repo_url}}" 
            dest: "~/dotfiles"
            force: yes
