- name: linux setup
  hosts: "{{ host }}"
  vars:
    apps:
      - discord
      - knowte
      - 1password
      - postman
      - curl
      - signal-desktop

    classic_apps:
      - code
      - android-studio

    packages:
      - git
      - ansible
      - quiterss
      - xclip
      - vim
      - conky-all

    photo_rec_url: "https://www.cgsecurity.org/testdisk-7.1.linux26-x86_64.tar.bz2"

    photo_rec_file_path: "~/Downloads/testdisk-7.1.linux26-x86_64.tar.bz2" 

    github_url: "https://github.com/ElQwerto110100100/toolbox"

    fav_theme: "Yaru-dark"

    fav_toolbar: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'code_code.desktop', 'org.gnome.Terminal.desktop', '1password_1password.desktop', 'install4j_a177y-BurpSuiteCommunity.desktop', 'discord_discord.desktop', 'gnome-control-center.desktop']"

  tasks:
    - name: Root Tasks
      block: 
        - name: Update all packages to their latest version
          apt:
            name: "*"
            state: latest

        - name: Upgrade the OS (apt-get dist-upgrade)
          apt:
            upgrade: dist

        - name: Install classic snaps
          snap:
            name: "{{ item }}"
          loop: "{{  classic_apps }}"

        - name: Install other snaps
          snap:
            name: "{{ item }}"
          loop: "{{ apps }}"

        - name: "Installing packages"
          apt:
            name: "{{ item }}"
          loop: "{{ packages }}"

        - name: "Get git toolbox"
          git:
            repo: "{{ github_url }}"
            dest: ~/tools/linux_tools/          
      become: yes

    - name: non root tasks
      block:
        - name: "Get photorec and teskDisc.tar"
          get_url:
            url: "{{ photo_rec_url }}"
            dest: "~/Downloads"
        
        - name: "Make tools dir"
          file:
            state: directory
            path: ~/tools

        - name: "Unpack"
          unarchive:
            src: "{{ photo_rec_file_path }}"
            dest: "~/tools/"
            remote_src: yes

        - name: "Remove file"
          file:
            state: absent
            path: "{{ photo_rec_file_path }}"
            
        - name: "Set dark theme"
          command: "gsettings set org.gnome.desktop.interface gtk-theme '{{ fav_theme }}'"
        
        - name: "Set favourite toolbar"
          command: 'gsettings set org.gnome.shell favorite-apps "{{ fav_toolbar }}" ' 
          tags: 'toolbar'

        - name: Set up cronky config
          copy:
            src: ./.files/conkyrc
            dest: ~/.conkyrc
          tags: conky

        - name: Set startup task
          copy: 
            src: ./files/conky.desktop
            dest: ~/.config/autostart/conky.desktop
          tags: conky

        - name: Set startup weather
          copy: 
            src: ./files/weather.desktop
            dest: ~/.config/autostart/weather.desktop

        - name: Copy rss feed list
          copy:
            src: ./files/mf-feeds.opml
            dest: ~/Documents
